### ISSUE TITLE
후기 등록-수정-삭제, 숙소 예약-취소-조회, 숙소 좋아요-취소 통신 연결

### ISSUE THREAD

**Issue by Pablaw** [cchloe0927/hanghaeBnB#50]
## Description
후기 등록-수정-삭제, 숙소 예약-취소-조회, 숙소 좋아요-취소 통신 연결 작업입니다.

## Todo
- [x] 후기 등록-수정-삭제 통신연결
- [x] 숙소 예약-취소-조회 통신연결
- [x]  숙소 좋아요-취소 통신 연결

## Etc
기타사항
